### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by leamas** [LiangYuen/Pi4j-RC522#3]
Hi!

I'm interested in using this code, but it's not clear to me if I can do it. So:

  - Can anyone use this code?
  - If so, under what conditions? 

The situation would be much clearer if you established that the code could be used according to a free license such as MIT or GPL.

**Comment by leamas** [comment]
HI, againPi4j-RC522!

There is not much feedback here, making it hard to reuse the code. Howevre, since you have published this on github you really need to use a free license. As long as I don't get any feedback from you my plan is to 

  - Clone your repo.
  - Add a copyright notice with your name, 2016
  - Add a GPLv3+ licensing; this is the most restrictive license I can think of which still is compatible with using github.

Please let me know if this is not acceptable, I'm ready to comply to whatever conditions you might assert for using  this code.

EDIT: restrictive -> most restrictive

**Comment by LiangYuen** [comment]
Yes,the code can be used by anyone under GPLv3 license.

**Comment by leamas** [comment]
OK, making a pull request that would clarify this. Besides that, not much to add here since your statement is clear (thanks!). Closing.
